version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb
      JWT_ACCESS_SECRET: change_me
      JWT_REFRESH_SECRET: change_me_too
      ACCESS_TOKEN_TTL: 15m
      REFRESH_TOKEN_TTL: 7d
      CORS_ORIGINS: http://localhost:3000
      FRONTEND_BASE_URL: http://localhost:3000
      DEFAULT_ROLE_NAME: operario
    ports:
      - "4001:4000"
    restart: unless-stopped

volumes:
  db_data:
